apiVersion: v1
kind: Service
metadata:
  name: my-j4kdemo-svc
  labels:
    app: j4kdemo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: j4kdemo
